
database_defaults: &database_defaults
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  database:
    <<: *database_defaults
    database: config/catalogue.development.sqlite

  log_level: <%= Logger::DEBUG %>
